### ISSUE TITLE
Kraker-js

### ISSUE THREAD

**Issue by Lexus89** [zzzteph/weakpass#13]
Hi,

The following error seems to prevent it from running:

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name'): assets/files-Bi_XU30g.js:18`

Hash used: 259745CB123A52AA2E693AAACCA2DB52 "12345678" (choosen online crack).

In addition, the workers/text.js file seems to be missing from the git repo.

**Comment by zzzteph** [comment]
Hello @Lexus89 !

Thanks - honestly, krack-js is under heavy development and still needs to be ready. It's not good that it was published before appropriate checks and in this draft state.
More updates will comming soon.

**Comment by zzzteph** [comment]
Hey-hey, I just pushed the final version of it. Check it out!

https://github.com/zzzteph/weakpass/pull/14
