### ISSUE TITLE
 20 Digits Wordlist for AVM Router 

### ISSUE THREAD

**Issue by Huibuh2010** [zzzteph/weakpass#2]
Hey Teph,

i'll create a custom wordlist specific for AVM Fritzbox 7490 and newer, i had installed a lot of Fritzbox and i have never seen 3 same digits in a row and 6 or more same digits on all 20 digits.

i know how to create 20 digit Wordlist but how can i create a 20 digit wordlist without 3 same digits in a row and not more then 6 same digits of all 20 digits.

thx for help

**Comment by zzzteph** [comment]
Hi! 
I don't think that such a wordlist exists, cause keyspace is quite large.
I'm not sure in math, but the very rough calculation shows that the keyspace will be 55*10^15, and the single password requires 20 bytes of data so you need **980 PB** of free space to store such a wordlist.
