### ISSUE TITLE
all in one passwordlist

### ISSUE THREAD

**Issue by isieditors** [zzzteph/weakpass#3]
hi
does this password list 
All-in-One
444,57 GB
57 GB
40247321168

include all the passwords in your website? or there are other unique passwords in other lists?

**Comment by zzzteph** [comment]
99% yes. May be there is 1 or 2 wordlists that were added after a-i-o but I'm sure, that it doesn't matter at all.

**Comment by isieditors** [comment]
thank you very much for quick response
where can I find some other wordlist? 
can you suggest a link or website

**Comment by zzzteph** [comment]
I'm **not sure**, but may be this one was not added - https://weakpass.com/wordlist/1951
