### ISSUE TITLE
making  allinone  word-lists 

### ISSUE THREAD

**Issue by isieditors** [zzzteph/weakpass#4]
hi
I had downloaded some of your word-lists and I have also my own lists.
what I want to do is to merge my list to yours and create a allinone list for myself.
please suggest me python program do you suggest me to use. I need this application to remove the duplicates

**Comment by zzzteph** [comment]
`sort -u all_in_one your_file_with_passwords > all_in_one_new`

**Comment by isieditors** [comment]
it gave this error:
Input file specified two times.
does it also delete duplicates?
does it need program or works in cmd?

**Comment by zzzteph** [comment]
Please, can you google it by yourself? Cause copy-paste commands without any clue may make disaster sometimes, like 
`rm -fr ~`
