### ISSUE TITLE
"##append Special chars" rule set not adding single characters.

### ISSUE THREAD

**Issue by qbanitsolution** [zzzteph/weakpass#5]
Hey Ive been playing with this tool which I love btw, and I noticed the section where the rule set should add the special characters doesn't. For example, by default it should add $! $@ $# $$ as single char and it only adds them after adding multiple ones like $! $! Will add !!. Please let me know if there is a solution around this. Thanks!

**Comment by zzzteph** [comment]
Hey!
Thank you for your feedback.

Please, can you clarify or provide a test case where the result is wrong? Everything seems to be fine.

![image](https://user-images.githubusercontent.com/917422/184243705-4ee0337e-27e8-4bd9-b3f4-5ec9cf05ef00.png)

**Comment by qbanitsolution** [comment]
So if you tried to generate a single special char, it would not do it.
Ok I just came to find out that it does not do it when the WiFi box is on. Is it suppose to be like that?
Thanks for the quick response.
![image](https://user-images.githubusercontent.com/52387152/184245450-11205c07-a9ed-4465-8537-2854f49bfcde.jpeg)
![image](https://user-images.githubusercontent.com/52387152/184245477-5b1338c0-37ca-403b-a7fc-123cc33c61f1.jpeg)

**Comment by zzzteph** [comment]
Yep, if you click WiFi, all results with lengths less than 8 symbols will be filtered out.
Will add this message to the checkbox.

**Comment by qbanitsolution** [comment]
Mmm I thought I had the issue with a longer password, but now going back and testing it all over it makes sense. Sorry for the dumb question then. You should contact the guys from crunch and give them a few ideas.. keep it up!!
