### ISSUE TITLE
How to use Weakpass_3 ?

### ISSUE THREAD

**Issue by zl9801** [zzzteph/weakpass#6]
Weakpass_3 is 28.2GB after decompression. Open it with UltraEdit to display hexadecimal, and use linux to display the file type data. How to transcode utf8?

**Comment by zl9801** [comment]
Weakpass_3 is 28.2GB after decompression. Use UltraEdit to open and display hexadecimal, and use linux to display file type data. How to transcode utf8? Use UltraEdit to open the Weakpass_3 file with garbled characters.

**Comment by zzzteph** [comment]
Hi. Sorry, I have no idea about UltraEdit.
