### ISSUE TITLE
Bad character in site

### ISSUE THREAD

**Issue by rodrigozanatta** [zzzteph/weakpass#8]
Could I write it here? I don't know. This is just to help...

This file has a problem: https://weakpass.com/wordlist/1696

It use character `#` and the browser can't decode. If you use `%23` URL code, it work. You need to use urlencode in the site with theses dificult characteres.

**Comment by zzzteph** [comment]
Hey @rodrigozanatta !

Awesome catch, much appreciated will fix it ASAP
